#

name: 👷 CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  TZ: Europe/Paris

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install bun
        uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2
      - run: bun install --frozen-lockfile
      - run: bun run build
      - run: bun run test:type-check
      - run: bun test
          --coverage
          --coverage-reporter=lcov
          --coverage-reporter=text
